"""API Request/Response Schemas — domain-split re-export.

All public names are re-exported here so that ``from api.schemas import X``
continues to work unchanged.
"""

# -- experiments (basic, molecule composition, batch, protocol) ----------------
from contracts.schema_enums import (  # noqa: F401
    CampaignStatus,
    RecommendationMode,
    RecommendationStatus,
    SimulationPriority,
    WaveStatus,
)

# -- re-export contracts.schemas types that were available in old api.schemas --
from contracts.schemas import (  # noqa: F401
    AmorphousBoundaryMode,
    CrystalCellMode,
    CrystalLayerSpec,
    CrystalMaterial,
    CrystalSourceType,
    FFType,
    LayerSourceType,
    MoleculeCountSpec,
    RunTier,
    StudyType,
    SurfaceOrientation,
)

# -- analysis (embedding, scatter, metrics) ------------------------------------
from .analysis import (
    AnalysisEmbeddingPoint,
    AnalysisEmbeddingResponse,
    ArrayMetricCompareItem,
    ArrayMetricCompareRequest,
    ArrayMetricCompareResponse,
    ArrayMetricDataResponse,
    ArrayMetricInfo,
    ArrayMetricsResponse,
    BinderCellMetricOverview,
    BinderCellXYSummaryPoint,
    BinderCellXYSummaryResponse,
    ExperimentArrayMetricEntry,
    MetricStatisticsResponse,
    MetricValueItem,
    MetricValuesResponse,
    Scatter3DPoint,
)

# -- analysis explorer ---------------------------------------------------------
from .analysis_explorer import (
    DatasetCatalogEntry,
    DatasetDimensionDef,
    DatasetMetricDef,
    ExplorerAggregateRequest,
    ExplorerAggregateResponse,
    ExplorerDataRequest,
    ExplorerDataResponse,
    ExplorerRangeFilter,
    ExplorerSortSpec,
)
from .experiments import (
    AdditiveInfo,
    BatchExperimentDetailItem,
    BatchExperimentRequest,
    BatchExperimentResponse,
    BatchJobBinderCellJobResponse,
    BatchJobBinderCellRequest,
    BatchJobBinderCellResponse,
    BinderCompositionDetailResponse,
    BinderTypeInfo,
    CompositionRequest,
    DefaultStagesResponse,
    DependentMoleculeExperimentRequest,
    DependentMoleculeExperimentResponse,
    DetailedHealthResponse,
    EInterRecommendationResponse,
    EquilibrationSettingsRequest,
    ExperimentCompositionResponse,
    ExperimentDetailResponse,
    ExperimentListItemResponse,
    ExperimentListResponse,
    ExperimentMoleculeDetailResponse,
    ExperimentRequest,
    ExperimentResponse,
    ExperimentStatusResponse,
    HealthResponse,
    JobStatusResponse,
    MoleculeCompositionPreviewRequest,
    MoleculeCompositionPreviewResponse,
    MoleculeCountItem,
    MoleculeExperimentRequest,
    MoleculeExperimentResponse,
    PropertyCalculationRequest,
    QueueStatsResponse,
    StageCondition,
    StageConfigResponse,
    StageDurationOverrideRequest,
    StageRequest,
    TypingChargePrecomputeItem,
    TypingChargePrecomputeRequest,
    TypingChargePrecomputeResponse,
)

# -- interface molecules --------------------------------------------------------
from .interface_molecules import (
    InterfaceMoleculeBatchGenerateRequest,
    InterfaceMoleculeBatchGenerateResponse,
    InterfaceMoleculeCellCreateRequest,
    InterfaceMoleculeCellListResponse,
    InterfaceMoleculeCellPreviewResponse,
    InterfaceMoleculeCellResponse,
    InterfaceMoleculeInfo,
    InterfaceMoleculeListResponse,
    InterfaceMoleculePreviewResponse,
)

# -- inverse design pipeline (plan/approve/progress/results) -------------------
from .inverse_pipeline import (
    InversePipelineApproveRequest,
    InversePipelineApproveResponse,
    InversePipelineLoopStepRequest,
    InversePipelineLoopStepResponse,
    InversePipelinePlanRequest,
    InversePipelinePlanResponse,
    InversePipelineProgressResponse,
    InversePipelineResultsResponse,
    PipelineMemberItem,
    PipelineProgressMemberItem,
)

# -- ML diagnostics / visualization ---------------------------------------------
from .ml_visualization import (
    DataCoverageResponse,
    DataQualityIssue,
    DataQualityResponse,
    FeatureImportanceItem,
    FeatureImportanceResponse,
    LearningCurvePoint,
    LearningCurveResponse,
    ParityPlotResponse,
    ParityPoint,
    ResidualResponse,
)

# -- recommendations (AL, inverse design) ------------------------------
from .recommendations import (
    ActiveLearningSummaryResponse,
    AggregateSpecRequest,
    ApproveRecommendationRequest,
    ApproveRejectResponse,
    CampaignCreateRequest,
    CampaignDetailResponse,
    CampaignListResponse,
    CampaignProgressResponse,
    CampaignSummary,
    CampaignWaveStatusResponse,
    CampaignWaveSubmitRequest,
    CompositionConstraintRequest,
    FeedResultRequest,
    InverseDesignRequest,
    InverseDesignResponse,
    InverseDesignResultItem,
    PropertyTargetItem,
    RecommendationBatchResponse,
    RecommendationDetailResponse,
    RecommendationItem,
    RejectRecommendationRequest,
    StopRecommendationRequest,
    TemperatureRangeRequest,
    UnifiedRecommendation,
)

# -- resources (GPU, recovery, settings, planning, ML, benchmark) --------------
from .resources import (
    AdditiveCoverageResponse,
    BenchmarkExpIdsResponse,
    BenchmarkReportResponse,
    BenchmarkValidationItem,
    DriftCheckResponse,
    ExecuteRecoveryRequest,
    GenerateWaveRequest,
    GPUInfoResponse,
    GPUStatsResponse,
    MLModelHistoryResponse,
    MLModelVersionResponse,
    RecoveryCheckResponse,
    RetrainRequest,
    RetrainResponse,
    SettingsResponse,
    SettingsUpdateRequest,
)

# -- structures (crystal, amorphous, layered) ----------------------------------
from .structures import (
    AmorphousCellComponentRequest,
    AmorphousCellCreateRequest,
    AmorphousCellListResponse,
    AmorphousCellPreviewResponse,
    AmorphousCellResponse,
    BoxPresetResponse,
    CrystalBatchGenerateRequest,
    CrystalBatchGenerateResponse,
    CrystalStructureCreateRequest,
    CrystalStructureListResponse,
    CrystalStructurePreviewResponse,
    CrystalStructureResponse,
    LayeredAnalysis3DPoint,
    LayeredAnalysis3DResponse,
    LayeredExperimentListResponse,
    LayeredExperimentResponse,
    LayeredStructureCheckResponse,
    LayeredStructurePreviewRequest,
    LayeredStructurePreviewResponse,
    LayeredStructureSubmitRequest,
    LayeredStructureSubmitResponse,
    LayerSourceInfo,
    LayerSourceListResponse,
    LayerSourceSummaryResponse,
    LayerStackItemRequest,
    LibraryVisibility,
    StressStrainResponse,
)

__all__ = [
    # analysis explorer
    "DatasetCatalogEntry",
    "DatasetDimensionDef",
    "DatasetMetricDef",
    "ExplorerAggregateRequest",
    "ExplorerAggregateResponse",
    "ExplorerDataRequest",
    "ExplorerDataResponse",
    "ExplorerRangeFilter",
    "ExplorerSortSpec",
    # experiments
    "BatchExperimentDetailItem",
    "BatchExperimentRequest",
    "BatchExperimentResponse",
    "CompositionRequest",
    "ExperimentCompositionResponse",
    "ExperimentDetailResponse",
    "ExperimentListItemResponse",
    "ExperimentListResponse",
    "ExperimentMoleculeDetailResponse",
    "ExperimentRequest",
    "ExperimentResponse",
    "ExperimentStatusResponse",
    "JobStatusResponse",
    "QueueStatsResponse",
    "SettingsResponse",
    "HealthResponse",
    "DetailedHealthResponse",
    "EInterRecommendationResponse",
    "BinderTypeInfo",
    "MoleculeCountItem",
    "BinderCompositionDetailResponse",
    "AdditiveInfo",
    "PropertyCalculationRequest",
    "StageDurationOverrideRequest",
    "StageRequest",
    "EquilibrationSettingsRequest",
    "MoleculeExperimentRequest",
    "DependentMoleculeExperimentRequest",
    "TypingChargePrecomputeRequest",
    "TypingChargePrecomputeItem",
    "TypingChargePrecomputeResponse",
    "MoleculeCompositionPreviewRequest",
    "MoleculeCompositionPreviewResponse",
    "MoleculeExperimentResponse",
    "DependentMoleculeExperimentResponse",
    "StageCondition",
    "StageConfigResponse",
    "DefaultStagesResponse",
    "BatchJobBinderCellRequest",
    "BatchJobBinderCellJobResponse",
    "BatchJobBinderCellResponse",
    # structures
    "CrystalBatchGenerateRequest",
    "CrystalBatchGenerateResponse",
    "CrystalStructureCreateRequest",
    "CrystalStructureResponse",
    "CrystalStructureListResponse",
    "CrystalStructurePreviewResponse",
    "AmorphousCellComponentRequest",
    "AmorphousCellCreateRequest",
    "AmorphousCellResponse",
    "AmorphousCellListResponse",
    "AmorphousCellPreviewResponse",
    "BoxPresetResponse",
    "LayerStackItemRequest",
    "LayerSourceInfo",
    "LayerSourceSummaryResponse",
    "LayerSourceListResponse",
    "LayeredAnalysis3DPoint",
    "LayeredAnalysis3DResponse",
    "LayeredExperimentResponse",
    "LayeredExperimentListResponse",
    "StressStrainResponse",
    "LayeredStructureCheckResponse",
    "LayeredStructurePreviewRequest",
    "LayeredStructurePreviewResponse",
    "LayeredStructureSubmitRequest",
    "LayeredStructureSubmitResponse",
    "LibraryVisibility",
    # analysis
    "AnalysisEmbeddingPoint",
    "AnalysisEmbeddingResponse",
    "BinderCellMetricOverview",
    "BinderCellXYSummaryPoint",
    "BinderCellXYSummaryResponse",
    "Scatter3DPoint",
    "MetricValueItem",
    "MetricValuesResponse",
    "MetricStatisticsResponse",
    "ArrayMetricCompareItem",
    "ArrayMetricCompareRequest",
    "ArrayMetricCompareResponse",
    "ArrayMetricDataResponse",
    "ArrayMetricInfo",
    "ArrayMetricsResponse",
    "ExperimentArrayMetricEntry",
    # recommendations
    "RecommendationItem",
    "RecommendationBatchResponse",
    "ApproveRecommendationRequest",
    "RejectRecommendationRequest",
    "StopRecommendationRequest",
    "ApproveRejectResponse",
    "UnifiedRecommendation",
    "RecommendationDetailResponse",
    "FeedResultRequest",
    "ActiveLearningSummaryResponse",
    "CampaignWaveSubmitRequest",
    "CampaignWaveStatusResponse",
    "CampaignProgressResponse",
    "CampaignCreateRequest",
    "CampaignSummary",
    "CampaignListResponse",
    "CampaignDetailResponse",
    "PropertyTargetItem",
    "CompositionConstraintRequest",
    "AggregateSpecRequest",
    "TemperatureRangeRequest",
    "InverseDesignRequest",
    "InverseDesignResultItem",
    "InverseDesignResponse",
    # inverse design pipeline
    "InversePipelineApproveRequest",
    "InversePipelineApproveResponse",
    "InversePipelineLoopStepRequest",
    "InversePipelineLoopStepResponse",
    "InversePipelinePlanRequest",
    "InversePipelinePlanResponse",
    "InversePipelineProgressResponse",
    "InversePipelineResultsResponse",
    "PipelineMemberItem",
    "PipelineProgressMemberItem",
    # resources
    "GPUInfoResponse",
    "GPUStatsResponse",
    "RecoveryCheckResponse",
    "ExecuteRecoveryRequest",
    "MLModelVersionResponse",
    "MLModelHistoryResponse",
    "DriftCheckResponse",
    "RetrainRequest",
    "RetrainResponse",
    "BenchmarkValidationItem",
    "BenchmarkReportResponse",
    "BenchmarkExpIdsResponse",
    "SettingsUpdateRequest",
    "AdditiveCoverageResponse",
    "GenerateWaveRequest",
    # interface molecules
    "InterfaceMoleculeBatchGenerateRequest",
    "InterfaceMoleculeBatchGenerateResponse",
    "InterfaceMoleculeCellCreateRequest",
    "InterfaceMoleculeCellListResponse",
    "InterfaceMoleculeCellPreviewResponse",
    "InterfaceMoleculeCellResponse",
    "InterfaceMoleculeInfo",
    "InterfaceMoleculeListResponse",
    "InterfaceMoleculePreviewResponse",
    # ML diagnostics
    "ParityPoint",
    "ParityPlotResponse",
    "FeatureImportanceItem",
    "FeatureImportanceResponse",
    "ResidualResponse",
    "LearningCurvePoint",
    "LearningCurveResponse",
    "DataCoverageResponse",
    "DataQualityIssue",
    "DataQualityResponse",
]
