import { LAYER_OPTIONAL_STAGES, LAYER_STAGES } from './config'

/**
 * Build the layer-geometry portion of the API payload (shared by preview and submit).
 */
export function buildLayerPayload(layers, xyTolerance, xyToZRatio, interLayerGap) {
  const normalizedLayers = layers.map((row, index) => ({
    source_type: row.sourceType,
    source_id: row.sourceId || null,
    auto_match_material: row.autoMatchMaterial || null,
    label: row.label?.trim() || null,
    gap_after_angstrom:
      index < layers.length - 1 && row.gapAfter !== '' ? Number(row.gapAfter) : null,
  }))
  return {
    layers: normalizedLayers,
    xy_tolerance_pct: Number(xyTolerance),
    min_xy_to_z_ratio: Number(xyToZRatio),
    inter_layer_gap_angstrom: Number(interLayerGap),
  }
}

/**
 * Build the complete submit payload.
 */
export function buildSubmitPayload({
  autoGeneratedName,
  layers,
  xyTolerance,
  xyToZRatio,
  interLayerGap,
  ffType,
  temperatureK,
  pressureAtm,
  zVacuum,
  seed,
  stageOverrides,
  layeredSelectedStages,
  tensilePullVelocity,
  tensileGripThickness,
  tensileMaxStrain,
  interactionAnalysis = null,
  eIntraMethod,
}) {
  const layerPayload = buildLayerPayload(layers, xyTolerance, xyToZRatio, interLayerGap)

  const filteredStageOverrides = stageOverrides.filter((item) =>
    LAYER_STAGES.includes(item.stage_name)
  )

  // Layered-specific: only send disabled optional stages
  const layeredStageRequests = LAYER_OPTIONAL_STAGES
    .filter((stage) => !layeredSelectedStages[stage])
    .map((stage) => ({ stage_key: stage, enabled: false }))

  // Build interaction_analysis payload if enabled
  const interactionAnalysisPayload = interactionAnalysis?.enabled
    ? {
        enabled: true,
        mode: 'gpu_then_cpu',
        metrics: interactionAnalysis.metrics || ['e_inter_layer_matrix'],
        auto_trigger_rerun: interactionAnalysis.auto_trigger_rerun ?? true,
      }
    : null

  return {
    name: autoGeneratedName,
    ...layerPayload,
    run_tier: 'screening',
    ff_type: ffType,
    e_intra_method: eIntraMethod,
    boundary_mode: 'ppf',
    temperature_K: Number(temperatureK),
    pressure_atm: Number(pressureAtm),
    z_vacuum_angstrom: Number(zVacuum),
    seed: seed === '' ? null : Number(seed),
    stage_durations: filteredStageOverrides,
    stage_requests: layeredStageRequests.length > 0 ? layeredStageRequests : undefined,
    tensile_enabled: layeredSelectedStages.tensile_pull || false,
    ...(layeredSelectedStages.tensile_pull
      ? {
          tensile_pull_velocity: Number(tensilePullVelocity),
          tensile_grip_thickness: Number(tensileGripThickness),
          tensile_max_strain: Number(tensileMaxStrain),
        }
      : {}),
    interaction_analysis: interactionAnalysisPayload,
  }
}

/** Check whether any layer is missing a required source selection. */
export function hasLayersMissingSources(layers, { requireSourceId = false } = {}) {
  if (requireSourceId) {
    return layers.some((row) => !row.sourceId)
  }
  return layers.some((row) => !row.sourceId && !row.autoMatchMaterial)
}
